language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
# for minibuf
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxcursor-dev