#[derive(PartialEq, Debug)]
pub enum Instruction {
    ClearDisplay,
    Return,
    Jump(u16),
    JumpV0Addr(u16),
    Call(u16),
    SkipEqVxByte(usize, u8),
    SkipEqVxVy(usize, usize),
    SkipKeyPressedVx(usize),
    SkipKeyNotPressedVx(usize),
    SkipNeqVxByte(usize, u8),
    SkipNeqVxVy(usize, usize),
    LoadRegsVx(usize),
    StoreRegsVx(usize),
    LoadBVx(usize),
    LoadDTVx(usize),
    LoadIAddr(u16),
    LoadSTVx(usize),
    LoadSpriteAddrVx(usize),
    LoadVxByte(usize, u8),
    LoadVxDT(usize),
    LoadVxKey(usize),
    LoadVxVy(usize, usize),
    AddIVx(usize),
    AddVxByte(usize, u8),
    AddVxVy(usize, usize),
    SubVxVy(usize, usize),
    SubnVxVy(usize, usize),
    XorVxVy(usize, usize),
    AndVxVy(usize, usize),
    OrVxVy(usize, usize),
    ShlVxby1(usize),
    ShrVxby1(usize),
    RandVxAndByte(usize, u8),
    DisplaySpriteVxVyNibble(usize, usize, u8),
}
