#[derive(Debug)]
pub enum Instruction {
    ClearDisplay,
    Return,
    Jump(u16),
    JumpV0Addr(u16),
    Call(u16),
    SkipEqVxByte(u8, u8),
    SkipEqVxVy(u8, u8),
    SkipKeyPressedVx(u8),
    SkipKeyNotPressedVx(u8),
    SkipNeqVxByte(u8, u8),
    SkipNeqVxVy(u8, u8),
    LoadRegsVx(u8),
    StoreRegsVx(u8),
    LoadBVx(u8),
    LoadDTVx(u8),
    LoadIAddr(u16),
    LoadSTVx(u8),
    LoadSpriteAddrVx(u8),
    LoadVxByte(u8, u8),
    LoadVxDT(u8),
    LoadVxKey(u8),
    LoadVxVy(u8, u8),
    AddIVx(u8),
    AddVxByte(u8, u8),
    AddVxVy(u8, u8),
    SubVxVy(u8, u8),
    SubnVxVy(u8, u8),
    XorVxVy(u8, u8),
    AndVxVy(u8, u8),
    OrVxVy(u8, u8),
    ShlVxby1(u8),
    ShrVxby1(u8),
    RandVxAndByte(u8, u8),
    DisplaySpriteVxVyNibble(u8, u8, u8),
}
